baseurl = "https://louismunro.com"
languageCode = "en-us"
title = "Louis Munro"
theme = "compass-lm"
MetaDataFormat = "toml"

[params] 
author = "Louis Munro" 
tagline = "Stating the obvious since 1974"
logo = "compass.png"
description = "Louis Munro's personal website"

